---
- name: Deploy SSH key and config to servers
  hosts: all
  tasks:
    - name: Gather user info
      command: "getent passwd {{ ansible_user }}"
      register: user_info

    - name: Set user home directory
      set_fact:
        user_home: "{{ user_info.stdout.split(':')[5] }}"
        user_uid: "{{ user_info.stdout.split(':')[2] }}"
        user_gid: "{{ user_info.stdout.split(':')[3] }}"

    - name: Ensure .ssh directory exists
      file:
        path: "{{ user_home }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ user_uid }}"
        group: "{{ user_gid }}"

    - name: Copy SSHKEY file to servers
      copy:
        src: /playbooks/files/ssh-keys/homelab
        dest: "{{ user_home }}/.ssh/"
        mode: '0600'
        owner: "{{ user_uid }}"
        group: "{{ user_gid }}"

    - name: Add SSH public key to authorized_keys
      lineinfile:
        path: "{{ user_home }}/.ssh/authorized_keys"
        line: "{{ lookup('file', '/playbooks/files/ssh-keys/homelab.pub') }}"
        create: yes
        mode: '0600'
        owner: "{{ user_uid }}"
        group: "{{ user_gid }}"

    - name: Copy SSH config file to servers
      copy:
        src: /playbooks/files/ssh-keys/config
        dest: "{{ user_home }}/.ssh/config"
        mode: '0600'
        owner: "{{ user_uid }}"
        group: "{{ user_gid }}"
